<template>
	<svg
		width="24"
		height="24"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
	>
		<g clip-path="url(#clip0_529_2866)">
			<rect
				x="7"
				y="8"
				width="10"
				height="8"
				rx="1"
				stroke="currentColor"
				stroke-width="2"
			/>
			<rect
				x="7"
				y="-4"
				width="10"
				height="8"
				rx="1"
				stroke="currentColor"
				stroke-width="2"
			/>
			<rect
				x="7"
				y="20"
				width="10"
				height="8"
				rx="1"
				stroke="currentColor"
				stroke-width="2"
			/>
		</g>
		<defs>
			<clipPath id="clip0_529_2866">
				<rect
					width="24"
					height="24"
					fill="white"
					transform="translate(0 24) rotate(-90)"
				/>
			</clipPath>
		</defs>
	</svg>
</template>
